version: '2'

services:
    openroberta_server:
        image: rbudde/openroberta_lab:${BRANCH}-${VERSION}
        ports:
            - "${SERVER_PORT_ON_HOST}:1999"
        command: ["-d", "database.uri=openroberta_db"]
        depends_on:
            - "openroberta_db"
        stop_signal: SIGINT
    openroberta_db:
        image: rbudde/openroberta_db:${BRANCH}-${VERSION}
        volumes:
            - "${DB_PARENTDIR}:/opt/db"
        ports:
            - "${DBSERVER_PORT_ON_HOST}:9001"
        stop_signal: SIGINT
